### ISSUE TITLE
Hyperlink Tooltip

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#100]
**Is your feature request related to a problem? Please describe.**
We need to style hyperlink text in the document, as well as create a popup tooltip for setting the link.

**Describe the solution you'd like**
There should be a popup tooltip _similar to_ the one used in Google Docs. Use this as a vague reference, we are not looking to exactly copy it.

![Screen Shot 2019-10-03 at 15 17 51 PM](https://user-images.githubusercontent.com/36460856/66157152-26a90180-e5f1-11e9-90f2-d3da944c8750.png)

**Describe alternatives you've considered**
N/A

**Additional context**
The tooltip that pops up for buttons in the toolbar currently were implemented in PR #66

**Comment by ahmedkrmn** [comment]
Can I work on this?

**Comment by ahmedkrmn** [comment]
Hi @irmerk, just a quick question to make sure I'm on the right track.
Currently the link pop up is a JavaScript `alert` that looks as follows:

_Add Link:_

![link](https://user-images.githubusercontent.com/20889958/66259192-62d59100-e7ae-11e9-8c05-6487f8ca5a59.PNG)
_Add Text:_


![text](https://user-images.githubusercontent.com/20889958/66259194-6537eb00-e7ae-11e9-945e-6212e333f0f6.PNG)

---

What you mean by **"Hyperlink Tooltip"** is that you want replace the two alerts with a single popup that looks similar to the one used in Google Docs?

**Comment by irmerk** [comment]
@ahmedkrmn yes, that's what I was thinking. And again, doesn't need to be _specifically_ like Google Docs, that's just an example. But definitely moving away from the alert style and more of a popup with text fields.

**Comment by ahmedkrmn** [comment]
@irmerk Can I use an `npm` React component or a JavaScript package, or should the new code be entirely written from scratch in JavaScript/CSS ?

**Comment by irmerk** [comment]
I'd hesitate to implement new libraries, especially if it's for this one component. We are utilizing `styled-components` and `CSS Grid` so far, though.

**Comment by irmerk** [comment]
This is open again. Any other contributor should view #108 as a starting point or for some context.

**Comment by sahalsaad** [comment]
Hi! I'll work on this issue. Thanks
