### ISSUE TITLE
Code Block Styling

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#101]
**Is your feature request related to a problem? Please describe.**
We need to style monospace or code block text in the document

**Describe the solution you'd like**
There should be the ability to style the monospace text via a prop

**Describe alternatives you've considered**
If possible, we should support block quotes and not just monospace text.

**Additional context**
A starting point for related code is in PR #65 and #66

**Comment by dkbuntzen** [comment]
Could I take this one?
