### ISSUE TITLE
Block Quote Styling

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#102]
**Is your feature request related to a problem? Please describe.**
We need to style block quote text in the document

**Describe the solution you'd like**
There should be the ability to style the block quote text via a prop

**Describe alternatives you've considered**
N/A

**Additional context**
A starting point for related code is in PR #65 and #66

**Comment by pramodrhegde** [comment]
Please assign this to me.

**Comment by pramodrhegde** [comment]
@irmerk Raised a PR here #113 

Please review.

**Comment by irmerk** [comment]
This issue is closed and continues in #125
