### ISSUE TITLE
ID Attribute Accessibility

### ISSUE THREAD

**Issue by monika** [accordproject/markdown-editor#109]
# WCAG 2.0 Level A [4.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html) (Parsing)

## Tasks
- All id attributes should only be used once.

## Related Issues:
- accordproject/template-studio-v2/issues/41
- accordproject/cicero-ui/issues/56

**Comment by irmerk** [comment]
Thank you for all your investigating on these issues @monika. Feel like this closes the issue?

**Comment by monika** [comment]
You're welcome, thanks for organizing such a great way to help via Hacktoberfest! This was my first time contributing to an open source project and it was very enjoyable and educational.

As far as the audit via [axe](https://www.deque.com/axe/) is showing me, there are no duplicated `id` attributes that it can see. I think this specific issue is closed, yeah! 

It might be worth adding a linter or unit test to check `id` attribute usage on components going forward, or run an audit on a semi-regular basis to just check that this is still the case.

**Comment by irmerk** [comment]
> It might be worth adding a linter or unit test to check `id` attribute usage on components going forward, or run an audit on a semi-regular basis to just check that this is still the case.

We have kicked the idea around before of doing a third party audit in the future. Definitely a topic for the weekly technology working group calls.
