### ISSUE TITLE
Toolbar Buttons Work in lockText Mode

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#122]
**Describe the bug**
Text formatting is currently being allowed during `lockText`

**To Reproduce**
1. Run locally within `cicero-ui`
  a. Download both `markdown-editor` and `cicero-ui`
  b. Run in `markdown-editor`
    - `npm install`
    - `npm run build`
    - `npm run transpile`
    - `npm link`
  c. Run in `cicero-ui`:
    - `npm install`
    - `rm -rf node_modules/\@accordproject/markdown-editor`
    - `npm link @accordproject/markdown-editor`
    - `npm run start`
2. Go to `http://localhost:8080/`
3. Ensure the `lockText` prop in `cicero-ui` being passed down to the `ContractEditor` is true.
4. Highlight text within a clause (not a variable), and try bolding or italicizing text.

**Expected behavior**
`lockText` should prevent any edits to text within a clause - except for variables

**Additional context**
N/A

**Comment by Ian-Yy** [comment]
Hi @irmerk , Can I try working on this issue? I'm still quite beginner. So, sorry if I made mistake 🙏

**Comment by irmerk** [comment]
@Ian-Yy any progress on this? Opening back up in the meantime.

**Comment by Ian-Yy** [comment]
@irmerk I'm still trying to figure out the link between cicero-ui and markdown-editor.

**Comment by irmerk** [comment]
> @irmerk I'm still trying to figure out the link between cicero-ui and markdown-editor.

Do you mean `npm link` for development? Or just the connection between the two?

**Comment by Ian-Yy** [comment]
Just the connection between the two. I can see when I toggle LockText, the state is changing true and false but thinking how the state is connected to markdown-editor

**Comment by Ian-Yy** [comment]
@irmerk And another thing to confirm. Do I need to keep running `npm link` everytime I change something in markdown-editor?

**Comment by irmerk** [comment]
@Ian-Yy once `markdown-editor` is linked, you'll just need to run `npm run transpile` in it to refresh the compiled build. 

I think the `lockText` value is passed to `markdown-editor` (`ContractEditor`), so that should be how they are connected.

**Comment by Ian-Yy** [comment]
> @Ian-Yy once `markdown-editor` is linked, you'll just need to run `npm run transpile` in it to refresh the compiled build.

@irmerk Thank you! This is what I'm looking for. Now I can continue debugging.

**Comment by Ian-Yy** [comment]
@irmerk I managed to make the text not bold and italicize when it's lockText, but I can still see the parseClause giving markdown text with bold and italicize symbol in it. 

For example, when I bold the `Acceptance`, it's not bold on screen but when I check the console, I can see it's `**Acceptance**` there.

So, I'm currently checking slateTransformer in Cicero UI. Please advise if I'm in the right direction.

**Comment by dselman** [comment]
I think we need to make the toolbar aware of lockText and conditionally wrap some of these commands. E.g. here:
https://github.com/accordproject/markdown-editor/blob/master/src/FormattingToolbar/index.js#L115

**Comment by Ian-Yy** [comment]
Ohh.. So, we should be checking for lockText in the onclick function calling toggleMark? Correct me if I'm wrong.

**Comment by irmerk** [comment]
That sounds right to me.

**Comment by jeromesimeon** [comment]
@irmerk is this resolved thanks to the latest PR?
