### ISSUE TITLE
First Keypress in lockText Mode Executes

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#123]
**Describe the bug**
Text formatting is currently being allowed during `lockText`

**To Reproduce**
1. Run locally within `cicero-ui`
  a. Download both `markdown-editor` and `cicero-ui`
  b. Run in `markdown-editor`
    - `npm install`
    - `npm run build`
    - `npm run transpile`
    - `npm link`
  c. Run in `cicero-ui`:
    - `npm install`
    - `rm -rf node_modules/\@accordproject/markdown-editor`
    - `npm link @accordproject/markdown-editor`
    - `npm run start`
2. Go to `http://localhost:8080/`
3. Ensure the `lockText` prop in `cicero-ui` being passed down to the `ContractEditor` is true.
4. Place selection within a clause, start typing. Notice the FIRST character key press executes.

**Expected behavior**
`lockText` should prevent any edits to text within a clause - except for variables

**Additional context**
N/A

**Comment by rishabhx64** [comment]
Can I take this up?

**Comment by pramodrhegde** [comment]
@irmerk Please assign this to me.

**Comment by irmerk** [comment]
@pramodrhegde any progress on this?

**Comment by pramodrhegde** [comment]
@irmerk Yes, I have started working on it. will raise a PR once I am ready with the fix.

**Comment by pramodrhegde** [comment]
@irmerk Please review.

**Comment by irmerk** [comment]
@pramodrhegde checking in on if there is any progress
