### ISSUE TITLE
Polish Editor Border and Shadow

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#124]
**Is your feature request related to a problem? Please describe.**
The editor should have some styling to appear more professional

**Describe the solution you'd like**
We should have smaller borders, no border radius, and a slight drop shadow.

**Describe alternatives you've considered**
A reference point is Google Docs

Current state:
<img width="798" alt="Screen Shot 2019-10-16 at 4 10 09 PM" src="https://user-images.githubusercontent.com/36460856/66954989-7d6dfc80-f02f-11e9-9f6b-833922779c31.png">

Google Docs (example):
<img width="1218" alt="Screen Shot 2019-10-16 at 4 11 56 PM" src="https://user-images.githubusercontent.com/36460856/66955105-b3ab7c00-f02f-11e9-9ee9-ad0e5554e907.png">

**Additional context**
Further input by @michael-grover

**Comment by Michael-Grover** [comment]
is this markdown editor meant to be used on its own or only as a component in other things like Template Studio?

**Comment by mttrbrts** [comment]
Is it in scope in this issue to tackle other UI polish issues like:
- font normalization between contract and clause text
- indentation of blockquotes
- background colors for parameters in lock-mode
- background color for smart clauses

**Comment by PseudoNerd** [comment]
Can I take this up ?

**Comment by Michael-Grover** [comment]
@irmerk this won't affect how the component looks in Template Studio V2 right?

**Comment by irmerk** [comment]
These can be added as optional props, similar to all the other styling props, to add flexibility to whoever uses the component.

**Comment by irmerk** [comment]
I believe these will be two separate issues:
1.
> * indentation of blockquotes
2.
> * font normalization between contract and clause text 
> * background colors for parameters in lock-mode
> * background color for smart clauses

**Comment by PseudoNerd** [comment]
> These can be added as optional props, similar to all the other styling props, to add flexibility to whoever uses the component.

![Screenshot from 2019-10-17 03-56-47](https://user-images.githubusercontent.com/26699089/66963911-922fac00-f092-11e9-9deb-6c5e96093f82.png)

Something like this?

**Comment by irmerk** [comment]
Yes, and the same for the border I would think.

**Comment by PseudoNerd** [comment]
I had a medical emergency, May I take this up again ?

**Comment by shrey-sachdeva2000** [comment]
Hi @irmerk, I have been working on this new UI. 

![UI](https://user-images.githubusercontent.com/47667325/75520558-d3b26980-5a2b-11ea-92ad-49d4ef2e5f44.jpg)

These are some things I focused upon in this design:
- Cleaning the toolbar with icons having equal proportions and similar style
- Increasing the editor width with more spacing
- Removing header styles from dropdown for better accessibility
- Removing border color and radius that made the design look slightly unprofessional

This is obviously very raw and could be worked upon from here. I would really appreciate your inputs on this.

**Comment by dselman** [comment]
Nice work. I suggest you create a PR – which will create a preview that people can play with on the server and provide input on.

**Comment by irmerk** [comment]
Agreed, put in a PR because this looks great so far!

**Comment by shrey-sachdeva2000** [comment]
Thanks @irmerk @dselman. I forgot to mention that this is just the design I made on Illustrator. I haven’t started working on the code yet, but if you like this I can surely go ahead with it.

**Comment by irmerk** [comment]
Oh oh I see. Okay well great. So far my initial points are:
- H1, H2, H3 should include an option for paragraph mode (P)
- Contrast for the clause template is a little off for accessibility
- I believe (could be wrong) that the width is controlled through props, so it could potentially be wider at the moment.

**Comment by Michael-Grover** [comment]
Looks good but I prefer the current styles dropdown 
![image](https://user-images.githubusercontent.com/40569793/75575331-e75ecf80-5a2d-11ea-8097-7cacb46f38ff.png)

**Comment by Michael-Grover** [comment]
Where would the markdown preview go?

![image](https://user-images.githubusercontent.com/40569793/75576353-33117900-5a2e-11ea-8063-87c9d1310267.png)

**Comment by irmerk** [comment]
This isn't about the markdown preview in the demo, but rather the contract editor itself which creates the right side of the demo.

**Comment by irmerk** [comment]
Oh and the styling changes for the clause template _would_ need to stay in `ClausePlugin` in `cicero-ui`

**Comment by shrey-sachdeva2000** [comment]
> Oh and the styling changes for the clause template _would_ need to stay in `ClausePlugin` in `cicero-ui`

Yes, I will start working on it and I could definitely use some help here if anyone is willing to work on this. @elit-altum?

**Comment by elit-altum** [comment]
> > Oh and the styling changes for the clause template _would_ need to stay in `ClausePlugin` in `cicero-ui`
> 
> Yes, I will start working on it and I could definitely use some help here if anyone is willing to work on this. @elit-altum?

Sure I'd love to work on this @shrey-sachdeva2000. You should proceed to create a Draft PR and we'd collaborate there?
@irmerk Should we shift this to Figma for easier reviews on the design?

**Comment by elit-altum** [comment]
How does this look for a start @irmerk ?

***Previous***
![image](https://user-images.githubusercontent.com/41413622/75610709-88867c80-5b39-11ea-9d88-5c1a13c5f8df.png)

***After***
![image](https://user-images.githubusercontent.com/41413622/75610684-5bd26500-5b39-11ea-9685-c456b82e97f1.png)

**Comment by irmerk** [comment]
@elit-altum I have not used Figma before, but that's up to you. I think the community can better comment and give feedback if there is a working PR. #247 seems to be a start for that. If someone wants to propose something for the styling of the clause template, that would be in `cicero-ui`.

**Comment by shrey-sachdeva2000** [comment]
**Changes**
- More subtle shadow on  Formatting Toolbar and Markdown Wrapper
- New icons for Redo, Undo and Quote
- Changed background color to dark for Toolbar Tooltip
- Changed color for icons when active

**Issues**
- Toolbar Tooltip edge is still white, it might be coming from Slate

**Proposal**
- Mention the shortcut commands for the formatting options inside Tooltip
- Make the Tooltips more descriptive, "Add a link", "Insert code" 

![toolbar](https://user-images.githubusercontent.com/47667325/75620537-f9687b80-5baf-11ea-92a8-536e2903b4ae.PNG)

**Comment by irmerk** [comment]
Closing issue. Open a new issue with some context if wanting to adjust styling.
