### ISSUE TITLE
Polish Indentation of Block Quotes

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#125]
**Is your feature request related to a problem? Please describe.**
Block quotes should have customizable indentation.

**Describe the solution you'd like**
Allow for props to dictate the indentation of the block quotes.

**Describe alternatives you've considered**
Open to input.

**Additional context**
More input by @mttrbrts, referenced in #124

**Comment by mbtamuli** [comment]
I'd like to work on this issue. Thanks

**Comment by irmerk** [comment]
@mbtamuli any progress on this? Opening back up for the time being.

**Comment by mbtamuli** [comment]
Hey @irmerk thanks for giving me the chance fix this.

I've added what I think is the requested changes as per the issue. https://github.com/accordproject/markdown-editor/pull/144

Should I also modify the example

https://github.com/accordproject/markdown-editor/blob/bf9324fb20dc2f680a2d68b643ce6856eada8473/examples/src/index.js#L50-L52


```
const propsObj = {
  WIDTH: '600px',
  BLOCKQUOTE: {
    INDENT: '15px',
  }
};
```

**Comment by jeromesimeon** [comment]
@irmerk is this resolved with the latest PR?
