### ISSUE TITLE
Double Enter Does Not Leave List

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#127]
**Describe the bug**
When writing in a numbered or bulleted list, pressing Enter twice does not escape the list.

**To Reproduce**
1. Go to [the Netlify deployed demo](https://accordproject-markdown-editor.netlify.com/examples/)
2. Click on `three` or `peaches` in the lists
3. Press Enter twice
4. See two bullets/numbers instead of escaping to a new paragraph line.

**Expected behavior**
Pressing enter twice at the end of a list should escape.

**Additional context**
N/A

**Comment by Sayan-dev** [comment]
i would like to work on it

**Comment by Sayan-dev** [comment]
can you specify the file where eventlistener function is working for taking keyboard inputs

**Comment by irmerk** [comment]
I believe it is `SlateAsInputEditor`, maybe start looking [here](https://github.com/accordproject/markdown-editor/blob/master/src/SlateAsInputEditor/index.js#L340)

**Comment by irmerk** [comment]
@Sayan-dev any progress on this? Opening back up in the meantime.
