### ISSUE TITLE
Display Selected Text Style

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#129]
**Is your feature request related to a problem? Please describe.**
The `Style` section of the toolbar should show what the selected text style is.

**Describe the solution you'd like**
The `Style` section of the toolbar should show what the selected header is **_if_** it is a heading, otherwise remain as `Normal Text`

This will require adapting the spacing of the toolbar to accommodate `Normal Text` and `Heading 1` 

Also hovering should result in a tooltip saying `Text Style`, and clicking should drop down the menu which currently opens on hover.

**Describe alternatives you've considered**
~This could be `H1`, `H2`, and `H3` to prevent it being longer than `Style` and messing with formatting~

Open to input

**Additional context**

Current state:

<img width="620" alt="Screen Shot 2019-10-17 at 1 42 50 PM" src="https://user-images.githubusercontent.com/36460856/67033583-18c0a980-f0e4-11e9-85ab-03f07f480fdb.png">

Current state on hover:

<img width="620" alt="Screen Shot 2019-10-17 at 1 43 00 PM" src="https://user-images.githubusercontent.com/36460856/67033588-1bbb9a00-f0e4-11e9-9e19-9dd90475c5c8.png">

**Comment by irmerk** [comment]
@michael-grover do you have any input on if this should even be a feature, and if it should have `Heading 1` or `H1`?

**Comment by Michael-Grover** [comment]
I'll look quickly at what other editors do but I think you're right @irmerk

**Comment by Michael-Grover** [comment]
![image](https://user-images.githubusercontent.com/40569793/67037586-cbe0d100-f0eb-11e9-8b0e-7463cf48f834.png)

fixed width, left aligned, "normal" by default, "style" in tooltip

**Comment by dkbuntzen** [comment]
@irmerk @Michael-Grover 
I am busy looking into this and was wondering if you one of you might be able to point me in the right direction here. Is there an established way that the editor or toolbar would understand what is currently selected. 

I don't want to over complicate this, and add methods if there is already some idea of this.

**Comment by irmerk** [comment]
Sure thing @dkbuntzen.

Granted a lot of this could use some refactoring, but I would start with what we're doing with marks [here](https://github.com/accordproject/markdown-editor/blob/master/src/FormattingToolbar/index.js#L199-L207) and how we set blocks to headers [here](https://github.com/accordproject/markdown-editor/blob/master/src/FormattingToolbar/index.js#L413-L428), maybe do something similar where we check the current selection and every time we determine whether the selection is a heading, and thus which heading to render in the toolbar.

**Comment by dkbuntzen** [comment]
@irmerk Thanks so much for the help, it really does assist.
