### ISSUE TITLE
Disallow H1 -> H3 -> H2

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#130]
**Is your feature request related to a problem? Please describe.**
We should have a restriction for creating out of order heading trees

**Describe the solution you'd like**
There should be some check on attempt to create a header which finds the nearest header above and below. If one of these results in nothing, allow. If they both exist, measure if they violate order.

This will likely involve code changes in [`cicero-ui`][cui] and/or [`template-studio-v2`][tsv2]

**Describe alternatives you've considered**
Open to input

**Additional context**
Currently allowed:
<img width="880" alt="Screen Shot 2019-10-17 at 1 52 47 PM" src="https://user-images.githubusercontent.com/36460856/67034467-bd8fb680-f0e5-11e9-98d6-521acc01622b.png">

[cui]: https://github.com/accordproject/cicero-ui
[tsv2]: https://github.com/accordproject/template-studio-v2

**Comment by husseyexplores** [comment]
I'd like to give this a shot as well!

There are quite a number of cases here, right? Like:
-  No above or below heading
 -- Allow every heading
- No heading below but exist above
  -- Then we need to make sure the entered heading is <= above
-No heading above but may exist below
  -- Then we need to make sure the entered heading is >= below
- Headings above and below which are different
 -- Then we need to make sure the entered heading is >= above and < below
- Headings above and below which are the same
 -- Then we need to make sure the entered heading is also the same.

**Comment by irmerk** [comment]
Yeah this is pretty confusing in my head... @michael-grover any input?

> * No heading below but exist above
>   -- Then we need to make sure the entered heading is <= above

At first I thought this sounded right, but an H3 could have an H1 below it, but not an H2 below it _unless_ it stems from a common H1?

> * No heading above but exist below
>   -- Then we need to make sure the entered heading is >= below
> * Headings above and below which are different (e.g between h1 and h2)
>   -- Then we need to make sure the entered heading is >= above and < below
> * Headings above and below which are the same (e.g between h2 and h2)
>   -- Then we need to make sure the entered heading is also the same.

Actually, while thinking up what edge cases there could be for all of these... Maybe it's the wrong approach to dictate which headers can be inserted. Maybe it's more about how we display them in the Navigation in `cicero-ui`? Again, wanting some feedback from @michael-grover and also @peterhunn

**Comment by peterhunn** [comment]
My two cents are that we shouldn't restrict the order in which headers that can be added, at least in the first instance. There could, in future, be the concept of a `section` that we may want to enforce some of these constraints in.

**Comment by Michael-Grover** [comment]
I agree with @peterhunn that header order shouldn't be restricted. Microsoft Word and Google Docs don't restrict this. If we had a section, subsection, subsubsection feature like Peter mentioned, then that should have an enforced order.

**Comment by irmerk** [comment]
Alright, closing this for now.
