### ISSUE TITLE
Copy + Paste Works in lockText Mode

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#132]
**Describe the bug**
Copy and pasting inside a clause template is currently being allowed during `lockText`

**To Reproduce**
1. Run locally within `cicero-ui`
  a. Download both `markdown-editor` and `cicero-ui`
  b. Run in `markdown-editor`
    - `npm install`
    - `npm run build`
    - `npm run transpile`
    - `npm link`
  c. Run in `cicero-ui`:
    - `npm install`
    - `rm -rf node_modules/\@accordproject/markdown-editor`
    - `npm link @accordproject/markdown-editor`
    - `npm run start`
2. Go to `http://localhost:8080/`
3. Ensure the `lockText` prop in `cicero-ui` being passed down to the `ContractEditor` is true.
4. Highlight text outside a clause (not a variable), and try pasting inside the clause.

**Expected behavior**
`lockText` should prevent any edits to text within a clause - except for variables

**Additional context**
Related to #122

**Comment by michaelclark2** [comment]
I'd like to take a crack at this

**Comment by irmerk** [comment]
@michaelclark2 any progress on this? Opening back up in the meantime.

**Comment by michaelclark2** [comment]
I'm close, I need to possibly make pull requests to both repos

**Comment by michaelclark2** [comment]
I've narrowed down the issue to the way you are adding the props.lockText as an annotation.  It gets unset somehow before it gets read in the isEditorLockText and I'm having trouble figuring out how to control that flow.  But figuring this out should prevent any changes to a clause while lockText === true

**Comment by michaelclark2** [comment]
I've got it to where it will prevent any changes, but only after adding a single character.  I added a preventDefault in the onKeyDown, and the character doesn't get added when I'm using a breakpoint, so maybe there's some asynchronicity going on somewhere?

**Comment by irmerk** [comment]
@michaelclark2 I think I know what you're referring to, #123. Is that what you're seeing? If so, yeah unsure what is causing that behavior at the moment.

I keep thinking there is a delay in setting the annotation and thus the first character is allowed, but skeptical of this theory.

**Comment by michaelclark2** [comment]
@irmerk yep, that's it.  I'll try to focus more on the copy paste side of this issue, but #123 should fix all the lockText issues (maybe)

**Comment by irmerk** [comment]
@michaelclark2 any progress on the copy/paste side of things?

**Comment by DianaLease** [comment]
I think this is exactly the same issue I fixed for disallowing "cut" within non-editable text, but for disallowing "paste" instead. So I can quickly take this one if it's open now.
