### ISSUE TITLE
Data-key is not set in heading tags

### ISSUE THREAD

**Issue by archhhh** [accordproject/markdown-editor#135]
**Describe the bug**
In heading node passed data-key is not set in heading tags, leading to scrolling bugs in template-studio-v2

**Expected behavior**
Heading tags should have attribute data-key='key', similar to clauses

Related to [@accordproject/template-studio-v2 issue #113](https://github.com/accordproject/template-studio-v2/issues/113)

**Comment by irmerk** [comment]
Closed with #136
