### ISSUE TITLE
Inline Hyperlink Tooltip

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#143]
**Is your feature request related to a problem? Please describe.**
The hyperlink tooltip should stem from the highlighted text inline which is being selected to convert into a hyperlink.

**Describe the solution you'd like**
Would it be possible for this UI to be placed above or below the text, so that it is easier for the user to tell which text is becoming a Hyperlink?

**Describe alternatives you've considered**
This will require investigation of [SlateJS](https://docs.slatejs.org/)

**Additional context**
Related Issues:
- #100

Screenshots:

![Screen Shot 2019-10-03 at 15 17 51 PM](https://user-images.githubusercontent.com/36460856/66157152-26a90180-e5f1-11e9-90f2-d3da944c8750.png)

![image](https://user-images.githubusercontent.com/40569793/67298295-0d40fa00-f4b9-11e9-86f4-3e669eab72f8.png)

**Comment by husseyexplores** [comment]
I will look into this and hopefully will open a PR regarding this shortly. I've researched the crux of the problem i.e getting the selected text position, will try to implement and see where things go.
