### ISSUE TITLE
Setting cursor when clicking on content area which does not have content

### ISSUE THREAD

**Issue by archhhh** [accordproject/markdown-editor#154]
**Is your feature request related to a problem? Please describe.**

Currently when you try to click on the content area which doesn't have any content, cursor disappears, or if you are out of focus and again try to click on the area, cursor does not appear.

**Describe the solution you'd like**

Setting cursor after the last character available, like it is in editors like Visual Studio Code or Microsoft Word.

**Comment by husseyexplores** [comment]
I would like to work on this as well. I've done the research on two possible fixes. (Feeling a bit excited as this is my first Hacktober fest which I'm really enjoying!! 🤓)

One possible fix is through just styling and adjusting the css. Making sure that the editor is 100% of the editor wrapper element.
The other is to listen for clicks and see if the target element is the wrapper element. If so, move the cursor to the end of the document though slate api.

Any preference which one should I work on? I'm not 100% sure if fixing it via CSS will have any quirks or not. Will need to see it in action.

**Comment by irmerk** [comment]
@husseyexplores Hmm, interesting. I could see either of those working, but the CSS will be more straightforward if it works - not having to make listeners. So maybe start with that route and hope there aren't quirks.
