### ISSUE TITLE
Pasting text from other text editors does not work as expected

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/markdown-editor#170]
**Describe the bug**
Pasting text from other text editors does not work as expected

**To Reproduce**
1. Paste a document from a document editor like Pages on Mac into the markdown editor
2. Attempt to change the style of only one paragraph

https://www.loom.com/share/01bff2319e994c128be19c49976d7e83

**Comment by Michael-Grover** [comment]
More detail: I tried pasting PDF content from Adobe Acrobat to the markdown editor and nothing was pasted. I had to paste the content into Apple Notes and then from Apple Notes to the markdown editor, which worked. @irmerk is this a separate issue?

**Comment by irmerk** [comment]
> @irmerk is this a separate issue?

Similar for sure, but I think because it's a PDF and this issue is text editors (like Word), it could be a separate issue and just link the two.

**Comment by irmerk** [comment]
Closing, reopen in `web-components` if still an issue.
