### ISSUE TITLE
Contract Editor Scrollbar is Obtrusive

### ISSUE THREAD

**Issue by V1shvesh** [accordproject/markdown-editor#175]
**To Reproduce**
1. Run locally with cicero-ui linked through npm link
2. Add enough line breaks to show the scroll bar, add twice as many more
3. Scroll to the bottom and notice the scrollbar background cutting into the toolbar

**Expected behavior**
The scrollbar should either have no background or begin below the toolbar

**Screenshots**
![](https://user-images.githubusercontent.com/36460856/67039170-cfc22280-f0ee-11e9-9ffe-bc978a9f1972.png)

**Additional context**
Linked to 
- [TSv2 Issue 114](https://github.com/accordproject/template-studio-v2/issues/114)
- [Cicero-UI Issue 188](https://github.com/accordproject/cicero-ui/issues/188)

**Comment by irmerk** [comment]
![Image from iOS](https://user-images.githubusercontent.com/36460856/67975376-53e5d100-fbea-11e9-85ae-c068c9a7e9bc.jpg)

Orange ([SlateAsInputEditor][slate]): 
- `markdown-editor`

Blue ([FormattingToolbar][format]):
- `markdown-editor`

Purple ([ContractEditor][cicero]):
- `cicero-ui`

Pink ([ContractEditorWrapper][tsv2]):
- `template-studio-v2`

**2** and **3** cross over the `FormattingToolbar`, which is the original issue. However, we want the scroll bar to be in this area to allow the `SlateAsInputEditor` to maintain a document feel. We need to figure out how to make the **2** scrollbar either sit under the `FormattingToolbar` or not extend up into it.

[slate]: https://github.com/accordproject/markdown-editor/tree/master/src/SlateAsInputEditor
[format]: https://github.com/accordproject/markdown-editor/tree/master/src/FormattingToolbar
[cicero]: https://github.com/accordproject/cicero-ui/tree/master/src/ContractEditor
[tsv2]: https://github.com/accordproject/template-studio-v2/blob/master/src/containers/ContractEditor/index.js#L15

**Comment by irmerk** [comment]
@V1shvesh any progress on this?
