### ISSUE TITLE
Render images inline

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#18]
If we have a link to an image we could attempt to render the image inline.

**Comment by jeromesimeon** [comment]
Do we have examples of contracts with diagrams?

**Comment by dselman** [comment]
This component is not specific to contracts. There will be another component for that.

**Comment by imbdb** [comment]
Please assign this to me.

**Comment by irmerk** [comment]
Moving this back to open after 11 days.

**Comment by dselman** [comment]
Resolved by https://github.com/accordproject/markdown-editor/commit/2ebe560da4a28a33a09a476df8bc1ea3c7fd5063
