### ISSUE TITLE
Handle Empty Backtick Codeblocks

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#189]
**Is your feature request related to a problem? Please describe.**
Trailing backticks are left in the markdown even if they do not have any content between them.

**Describe the solution you'd like**
Empty backticks should be removed during the transform.

**Slate Value in the `ContractEditor`**
<img width="331" alt="Screen Shot 2019-11-12 at 16 40 53 PM" src="https://user-images.githubusercontent.com/36460856/68713193-4c6be380-056b-11ea-850e-09bf12f1b2d0.png">

**Markdown after pass through `SlateTransformer`**
```
This is the contract `editor`. You can edit this text!

`code here`

`more code there`

``

`last code line`

Not code
```

**Comment by irmerk** [comment]
This will be solved in the short term by exiting `codespan` when pressing enter.

**Comment by dselman** [comment]
We may need to support multi line code blocks using three back ticks.

**Comment by irmerk** [comment]
Correct, though that will probably be a different issue. And at the moment it's unclear to me if contracts will have much need for them.

Either way I plan on creating a separate issue to track that.

**Comment by dselman** [comment]
Sounds good. This editor is not just for contracts...

**Comment by jeromesimeon** [comment]
> Correct, though that will probably be a different issue. And at the moment it's unclear to me if contracts will have much need for them.
> 
> Either way I plan on creating a separate issue to track that.

https://github.com/accordproject/markdown-editor/issues/190
