### ISSUE TITLE
Markdown support: Nested lists

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-editor#191]
**Is your feature request related to a problem? Please describe.**
Markdown documents often include lists, and sometimes nested lists.

It would be nice if the editor allowed creating/editing/deleting nested lists.

**Describe the solution you'd like**
The ability to create and edit a nested lists.

It would be nice to have a convenient way to switch between nesting levels.

**Describe alternatives you've considered**

**Additional context**

**Comment by DianaLease** [comment]
closing because duplicate of https://github.com/accordproject/markdown-editor/issues/195
