### ISSUE TITLE
Slate Losing Lists

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#192]
**Describe the bug**
There seems to be an error with the schema for SlateJS and lists are lost when coming from markdown to slate in the `markdown-transform`

**To Reproduce**
Roundtrip Slate DOM to markdown back to Slate DOM

**Expected behavior**
There should be rendering of list items correctly, not as paragraphs?

**Screenshots**
<img width="615" alt="Screen Shot 2019-11-13 at 14 53 30 PM" src="https://user-images.githubusercontent.com/36460856/68799036-7bdf2680-0625-11ea-948e-2a6a8a997326.png">
Note that the indentation is way off after a list now.

<img width="608" alt="Screen Shot 2019-11-13 at 14 53 42 PM" src="https://user-images.githubusercontent.com/36460856/68799040-7da8ea00-0625-11ea-8f32-ded084b8a6c4.png">
Note that this is not being registered as a list in the toolbar, and entering creates a plain paragraph (indented)

**Comment by irmerk** [comment]
In the demo you can see that the list already created and there in the demo renders with a paragraph tag, but a new list created by the user has list items which are _not_ paragraph tags:

---

**Default list**:
<img width="1079" alt="Screen Shot 2019-11-14 at 17 23 38 PM" src="https://user-images.githubusercontent.com/36460856/68901355-c7680200-0703-11ea-9356-7c4fbe4d372f.png">

---

**User made list**:
<img width="1087" alt="Screen Shot 2019-11-14 at 17 23 13 PM" src="https://user-images.githubusercontent.com/36460856/68901338-c040f400-0703-11ea-9623-292c3c494990.png">

---

The default ones are not registering as a list to the toolbar because it is being recognized as just a paragraph.

**Comment by jeromesimeon** [comment]
This looks like a regression introduced when we switched to markdown-transform 0.8.0.

**Comment by irmerk** [comment]
Right, this seems to have to do with needing to update the way we handle lists in this component now. Because it used to be 
```
ol_list => list_item => text
```
But now is
```
ol_list => list_item => paragraph => text
```

**Comment by jeromesimeon** [comment]
makes sense! The relationship between the schema and how we modify the DOM is also pretty sensitive. I'm wondering if there is a good way to document both so they remain in sync.
