### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#2]
We need unit tests for the JSON <-> MD conversion

**Comment by jeromesimeon** [comment]
Any thought about how those would be written? Using jest or more traditional mocha-style tests?

**Comment by jeromesimeon** [comment]
Roundtrip tests would be useful. To answer my own question, jest seems like a fine choice. Here is a small example:

```
test('can roundtrip basic text', () => {
  const markdownText = 'This is some text.';
  const value = fromMarkdown.convert(markdownText);
  const markdownRound = toMarkdown.convert(value);
  expect(markdownRound).toEqual(markdownText);
});
```

Note that even that first test fails round-tripping:
```
  ● can roundtrip basic text

    expect(received).toEqual(expected) // deep equality

    Expected: "This is some text."
    Received: "This is some text.

    "
```

This may tie into some of the whitespace issues mentioned in https://github.com/accordproject/cicero-ui/issues/43

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by codingdefined** [comment]
@irmerk I would like to work on it. Does the tests should be only on the JSON <-> MD conversion? What all scenarios should we consider for the testing, like all the buttons in the toolbar?

**Comment by irmerk** [comment]
@codingdefined this would be great to pick up! Just keep aware of the changes we're making in PRs #114 and #117 over the next few days. 

We're using the [`markdown-transform`](https://github.com/accordproject/markdown-transform) now, so the conversions are described more in that README. I think the more tests the better, essentially. Testing buttons, testing copy-pasting, testing adding a clause template... If you'd use the editor in X way, we should test X.

**Comment by codingdefined** [comment]
@irmerk Created the pull request for the same.

**Comment by irmerk** [comment]
As mentioned in #134, this issue can provide for many PRs, so I will open this up.

**Comment by irmerk** [comment]
Please note the conversation in [`markdown-transform` #117](https://github.com/accordproject/markdown-transform/issues/117) for testing this repo.

**Comment by irmerk** [comment]
Closing for https://github.com/accordproject/web-components/issues/14
