### ISSUE TITLE
PASTE: handle lists

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#207]
Input (https://www.bbc.co.uk/news/business-50723392):

SoftBank declined to comment on the reports. Wag did not immediately reply to a request for comment from the BBC.
- What you need to know about Softbank's IPO
- WeWork investor: My judgment was not right
- WeWork seals multi-billion-dollar rescue deal

Error:
[Error] ValidationException: Instance undefined missing required field tight
	reportMissingRequiredProperty (resourcevalidator.js:33)
	visitClassDeclaration (resourcevalidator.js:180)
	checkItem (resourcevalidator.js:347)
	checkArray (resourcevalidator.js:274)
	visitField (resourcevalidator.js:220)
	visitClassDeclaration (resourcevalidator.js:176)
	validate (validatedconcept.js:128)
	fromJSON (serializer.js:187)
	fromCiceroMark (SlateTransformer.js:884)
	onPaste (index.js:450)
	next (slate.es.js:11164)
	onEvent (slate-react.es.js:1845)
	callCallback (react-dom.development.js:336)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:385)
	invokeGuardedCallback (react-dom.development.js:440)
	invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:454)
	executeDispatch (react-dom.development.js:584)
	executeDispatchesInOrder (react-dom.development.js:609)
	executeDispatchesAndRelease (react-dom.development.js:713)
	forEachAccumulated (react-dom.development.js:694)
	runEventsInBatch (react-dom.development.js:739)
	runExtractedPluginEventsInBatch (react-dom.development.js:880)
	handleTopLevel (react-dom.development.js:5807)
	batchedEventUpdates$1 (react-dom.development.js:24368)
	batchedEventUpdates (react-dom.development.js:1419)
	dispatchEventForPluginEventSystem (react-dom.development.js:5898)
	attemptToDispatchEvent (react-dom.development.js:6014)
	dispatchEvent (react-dom.development.js:5918)
	dispatchEvent
	unstable_runWithPriority (scheduler.development.js:818)
	discreteUpdates$1 (react-dom.development.js:24384)
	discreteUpdates (react-dom.development.js:1442)
	dispatchDiscreteEvent (react-dom.development.js:5885)
	dispatchDiscreteEvent

**Comment by jeromesimeon** [comment]
I think this one was fixed in: https://github.com/accordproject/markdown-transform/pull/141/files

Here is a snapshot from the BBC:

<img width="765" alt="Screenshot 2019-12-11 at 10 45 24 AM" src="https://user-images.githubusercontent.com/670099/70636533-b4adf380-1c03-11ea-8f85-8146f79a6c52.png">
