### ISSUE TITLE
PASTE: handle images

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#208]
Input (https://www.bbc.co.uk/news/business-50723392):

**Select the image and the para just below it**
Wag! App Walk Report CardImage copyrightWAG INC.
Technology giant SoftBank has reportedly agreed to sell its stake in dog-walking app Wag.

Error:
[Error] TypeError: firstChild.hasBlockChildren is not a function. (In 'firstChild.hasBlockChildren()', 'firstChild.hasBlockChildren' is undefined)
	rethrowCaughtError (react-dom.development.js:6284)
	runEventsInBatch (react-dom.development.js:748)
	runExtractedPluginEventsInBatch (react-dom.development.js:880)
	handleTopLevel (react-dom.development.js:5807)
	batchedEventUpdates$1 (react-dom.development.js:24368)
	batchedEventUpdates (react-dom.development.js:1419)
	dispatchEventForPluginEventSystem (react-dom.development.js:5898)
	attemptToDispatchEvent (react-dom.development.js:6014)
	dispatchEvent (react-dom.development.js:5918)
	dispatchEvent
	unstable_runWithPriority (scheduler.development.js:818)
	discreteUpdates$1 (react-dom.development.js:24384)
	discreteUpdates (react-dom.development.js:1442)
	dispatchDiscreteEvent (react-dom.development.js:5885)
	dispatchDiscreteEvent

**Comment by dselman** [comment]
Maybe a duplicate of #209

**Comment by irmerk** [comment]
This seems to be resolved.
