### ISSUE TITLE
PASTE: handle input from a foreign Slate editor

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#210]
Input (https://www.slatejs.org/examples/richtext):

This is editable rich text, much better than a <textarea>!Since it's rich text, you can do things like turn a selection of text bold, or add a semantically rendered block quote in the middle of the page, like this:A wise quote.Try it out for yourself!My HeadingThis is text. This is italic text. This is bold text. This is a link. This is inline code.This is bold and italic text.This is a softbreak.This is alinebreak.This is a quote.Heading TwoThis is more text.Ordered lists:onetwothreeOr:applespearspeachesSub headingThis is more text.Fin.

Error:
[Error] Error: `Node.fromJSON` requires an `object` of either 'block', 'document', 'inline' or 'text', but you passed: [object Object],[object Object],[object Object],[object Object],[object Object]
	fromJSON (slate.es.js:3277)
	deserializeNode (slate-base64-serializer.es.js:56)
	getEventTransfer (slate-react.es.js:3876:109)
	onPaste (index.js:442:91)
	next (slate.es.js:11164)
	onEvent (slate-react.es.js:1845)
	callCallback (react-dom.development.js:336)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:385)
	invokeGuardedCallback (react-dom.development.js:440)
	invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:454)
	executeDispatch (react-dom.development.js:584)
	executeDispatchesInOrder (react-dom.development.js:609)
	executeDispatchesAndRelease (react-dom.development.js:713)
	forEachAccumulated (react-dom.development.js:694)
	runEventsInBatch (react-dom.development.js:739)
	runExtractedPluginEventsInBatch (react-dom.development.js:880)
	handleTopLevel (react-dom.development.js:5807)
	batchedEventUpdates$1 (react-dom.development.js:24368)
	batchedEventUpdates (react-dom.development.js:1419)
	dispatchEventForPluginEventSystem (react-dom.development.js:5898)
	attemptToDispatchEvent (react-dom.development.js:6014)
	dispatchEvent (react-dom.development.js:5918)
	dispatchEvent
	unstable_runWithPriority (scheduler.development.js:818)
	discreteUpdates$1 (react-dom.development.js:24384)
	discreteUpdates (react-dom.development.js:1442)
	dispatchDiscreteEvent (react-dom.development.js:5885)
	dispatchDiscreteEvent

**Comment by irmerk** [comment]
Seems resolved.
