### ISSUE TITLE
Ability to open links

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-editor#213]
**Is your feature request related to a problem? Please describe.**
I think it would be nice to be able to open links from the editor.
As far as I can tell right now there is only a way to edit a link, not to open it.

<img width="333" alt="Screenshot 2019-12-18 at 5 04 55 PM" src="https://user-images.githubusercontent.com/670099/71127758-a76fa680-21b9-11ea-96e4-ec45986b3349.png">

**Describe the solution you'd like**
Ability to open a link (through a click on the link itself or a button).

**Comment by jeromesimeon** [comment]
For instance in Google docs:

<img width="669" alt="Screenshot 2020-02-12 at 9 35 01 AM" src="https://user-images.githubusercontent.com/670099/74344711-034e4a00-4d7b-11ea-83f2-ccba6681fbc8.png">

In order from left to right you can:
1. Click to open the link in a new tab
2. Copy the link
3. Edit the link
4. Remove the link

**Comment by 98lenvi** [comment]
Can I try?

**Comment by dselman** [comment]
> Can I try?

Assigned to you. Thanks!

**Comment by dselman** [comment]
Google Docs is another source of inspiration.
