### ISSUE TITLE
Paragraph Deletion Before Header Removes Header

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#217]
**Describe the bug**
Triple clicking a paragraph before a header and deleting removes the header from that element

**To Reproduce**
1. Run `markdown-editor` locally (or within `cicero-ui`)
2. Create two paragraphs, make the second one a header
3. Triple click the paragraph and press backspace
4. The header is now a normal paragraph

**Expected behavior**
This shouldn't be removing the header element

**Comment by elit-altum** [comment]
@irmerk I am not able to recreate this issue, is it fixed ?

**Comment by irmerk** [comment]
@elit-altum I believe so, I cannot recreate now either. Unsure what fixed this.
