### ISSUE TITLE
Various issues with deletion (character per character)

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-editor#223]
**Describe the bug**
When deleting text, things sometimes go wrong.

**To Reproduce**
1. Go to the demo
2. Delete the content of an item, cannot fully delete
3. Go to the softbreak/linebreak paragraphs and delete
4. Some strange markdown results...

**Expected behavior**
Ability to delete consistently.

**Comment by jeromesimeon** [comment]
Note that the issues for deleting inside lists seems to be browser dependent. We can delete the list item in Safari but not in Chrome.

Tried on the latest: https://accordproject-markdown-editor.netlify.com/examples/

**Comment by dselman** [comment]
Going to take a look at this one.

**Comment by jeromesimeon** [comment]
To confirm: this also fixes issues with deletion inside lists but _not_ for thematic breaks.

**Comment by dselman** [comment]
> To confirm: this also fixes issues with deletion inside lists but _not_ for thematic breaks.

Ok, thanks. I'll take a look at thematic breaks next.
