### ISSUE TITLE
Optionally hide the markdown tab/pane

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#23]
Some users will want to limit the users to only editing using the rich text pane.

**Comment by jeromesimeon** [comment]
An options menu might be nice (e.g., markdown on flag, show compiled ergo flag)?

**Comment by dselman** [comment]
I will add a `props` so that the "Edit" toggle can be hidden.

**Comment by johnnyqbui** [comment]
is this one still open? I'd like to take this.

**Comment by irmerk** [comment]
@dselman I believe this issue may be out of date? It sounds like it relates to #79 a bit.

**Comment by irmerk** [comment]
I think go for it @johnnyqbui if you still want to. It seems like this does in fact relate to #79 and this comment I made here https://github.com/accordproject/markdown-editor/pull/112#issuecomment-542854144
