### ISSUE TITLE
Deleting everything still leaves an empty title

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-editor#240]
**Describe the bug**
Opening the editor demo and deleting everything results in an empty title (with some unexpected markdown).

**To Reproduce**
1. Go to the markdown-editor demo
2. Select everything
3. Delete (with backspace)
4. It still shows a title, and the markdown is `====` which will _not_ correspond to an empty title so it's inconsistent.

**Expected behavior**
It should delete everything.

**Screenshots**
<img width="1490" alt="Screenshot 2020-02-17 at 11 04 17 AM" src="https://user-images.githubusercontent.com/670099/74669512-43e00600-5175-11ea-9a6d-f3c43707cb1b.png">

**Comment by 98lenvi** [comment]
Hi @jeromesimeon, I had one more observation about the behavior.

In the editor when you delete everything, The markdown will show the symbol for the topmost string, i.e. if the topmost was a `Heading 1`, then the markdown would be `===`, similarly, if it was `block-quote`, it will show a markdown with `>`

In google docs, the behavior would be an empty string of the currently selected format.

I'm interested in solving this issue, but I'm not sure whether I will be able to do so.

**Comment by irmerk** [comment]
@98lenvi take a stab at it and let us know what you run into!

**Comment by 98lenvi** [comment]
Sure! @irmerk

**Comment by shakti97** [comment]
Can I work on this issue?

**Comment by irmerk** [comment]
That's a question for @98lenvi I believe. Are you still working on this?

**Comment by irmerk** [comment]
I think hold off on this for the [Slate migration](https://github.com/accordproject/markdown-editor/issues/297)

**Comment by irmerk** [comment]
@98lenvi @nik72619c @shakti97:

#357 (and accordproject/markdown-editor#297) has been finished, so there is no longer a blocker on this issue. The migration _may_ have solved this issue, so look into that first.

**Comment by irmerk** [comment]
This looks solved.

**Comment by jeromesimeon** [comment]
> This looks solved.

Magic of Slate57? Does it keep a text node around?
