### ISSUE TITLE
Support keyboard shortcuts

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#244]
Add keyboard shortcuts for common formatting commands, like bold, italics etc.

**Comment by irmerk** [comment]
Repopening for adding documentation for this in the `README`

Also, a thought: Is there a way to support users creating their own hotkeys?

**Comment by 98lenvi** [comment]
@irmerk, we can maybe support re-mapping of hotkeys, but for adding new hotkeys, it will be a challenge. And even if the user enters custom hotkeys, where do we store it? I think storing in localStorage would be the best option.

**Comment by irmerk** [comment]
That makes sense @98lenvi. I think the documentation is probably a better goal for right now and we can open an issue around creating hotkeys if a user actually requests it.

**Comment by 98lenvi** [comment]
@irmerk, Where would you like to place this in the readme? I think after examples, would be a good place. Do you want to have a separate file(constants) that has the keyboard shortcuts in it (making it easier for the user to modify it), and provide documentation for editing that one too(like styles)?

**Comment by irmerk** [comment]
Hmm I think just before "Demo" here https://github.com/accordproject/markdown-editor#demo would be good for a "Shortcuts" section.

I think I like that direction, but it doesn't seem very necessary right now.

**Comment by 98lenvi** [comment]
Okie, I'll take it up 😎 !
