### ISSUE TITLE
Keyboard Shortcut for Links

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#249]
Support for adding a link via the keyboard.

#### Notes from @98lenvi:
- Link Keyboard shortcut is not implemented, I think we need to refactor the code as the methods for rendering the Link popover resides in `FormattingToolbar` which is a child of of the `Editor` where I am providing the `KeyDown` conditions.
- Refactoring can be moving the `renderLinkSetForm()` of the link popover to a new component file.

**Comment by elit-altum** [comment]
I'd like to work on this once

**Comment by irmerk** [comment]
@elit-altum what is the status on this one?

**Comment by elit-altum** [comment]
@irmerk This shortcut has been added after the slate v57 update. We can close this now!
