### ISSUE TITLE
Protocol and library spelling mistake in readme

### ISSUE THREAD

**Issue by kanav-raina** [accordproject/markdown-editor#251]
![protocol_and_library_in_markdown_editor](https://user-images.githubusercontent.com/29794748/75627295-f5ab1800-5bf4-11ea-83e2-2ccaf2983026.png)
![protocol_and_library_in_markdown_editor_2](https://user-images.githubusercontent.com/29794748/75627300-fcd22600-5bf4-11ea-985f-4c75c953bad0.png)

**Comment by irmerk** [comment]
This is likely the case for all repos that have this section in the README, so PRs for all those would be necessary and we can approve them all at the same time.

**Comment by irmerk** [comment]
Review the contribution guidelines [here](https://github.com/accordproject/markdown-editor/blob/master/CONTRIBUTING.md)

**Comment by kanav-raina** [comment]
I have updated the spelling 

cicero                                        done
ergo                                          done
concerto                                    done
markdown-editor                       done
cicero-template-library              already correct
model   library_spelling             done
techdocs                                   already correct
cicero-vscode-extension           already correct
cicero-ui                                    done
concerto-ui                                done
template-studio-v2                    already correct
