### ISSUE TITLE
Selecting list/quote option while link popup is open crashes demo

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#266]
**Describe the bug**
Opening the editor and selecting any list type (numbered/bulleted) or quote while the link popup is open crashes the demo

**To Reproduce**
1. Go to the markdown-editor-ui demo
2. Click on the pre-existing template link to open the popup
3. Click on any list type or quote
4. Demo crashes

**Expected behavior**
Ideally an error/prompt should be produced or no action should be taken

**Screenshots**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/47667325/76126939-71a6c500-6026-11ea-93a7-2b4a74f320be.gif)

**Error Log**
![erroscs](https://user-images.githubusercontent.com/47667325/76127253-39ec4d00-6027-11ea-80b1-aafccfd41ea0.PNG)

**Comment by irmerk** [comment]
Ah thank you for this find! This is a bad one, need to look at this ASAP.

**Comment by 98lenvi** [comment]
Assign this to me! I'm in progress of finding a fix
