### ISSUE TITLE
Removing link followed by Undo shortcut crashes demo

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#272]
**Describe the bug**
Opening the editor and removing the templated link from popup followed by Undo shortcut (Ctrl+Z) crashes the demo.

**To Reproduce**
1. Go to `markdown-editor` demo
2. Click on the templated link 
3. Click on 'Remove' from the popup
3. Press Ctrl + Z (Undo command)
4. Demo crashes

**Expected behavior**
Preferably, the link should be restored.

**Screenshots**
![link_crash](https://user-images.githubusercontent.com/47667325/76261160-67cbce80-627f-11ea-8973-3c8737c3a8a0.gif)

**Comment by dselman** [comment]
I'd like to understand *why* the editor is crashing. Probably related to how we are adding the link...
