### ISSUE TITLE
Lists items with anything but a single paragraph are not rendered properly

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-editor#273]
**Describe the bug**
List items containing more than one paragraph (or other kinds of nodes) are wrongly rendered as multiple items of the list.

This is a regression, I believe introduced in `0.9.11`.

**To Reproduce**
1. Open the editor with the following markdown

```
1. one

   one/two

   one/three

   ------

   one/four
2. two
```

In the Markdown dingus:
<img width="909" alt="Screenshot 2020-03-09 at 6 36 21 PM" src="https://user-images.githubusercontent.com/670099/76263305-ee0ef300-6234-11ea-8b7f-74761f84f284.png">

In Markdown Editor 0.9.10:
<img width="291" alt="Screenshot 2020-03-09 at 6 39 08 PM" src="https://user-images.githubusercontent.com/670099/76263449-4d6d0300-6235-11ea-852c-401ef00d8b75.png">

In Markdown Editor 0.9.11:
<img width="749" alt="Screenshot 2020-03-09 at 6 29 57 PM" src="https://user-images.githubusercontent.com/670099/76263380-20b8eb80-6235-11ea-9122-d1eb7e7d16cf.png">

**Comment by jeromesimeon** [comment]
I believe this is due to the new rendering for list introduced in https://github.com/accordproject/markdown-editor/pull/269

**Comment by elit-altum** [comment]
> 
> 
> I believe this is due to the new rendering for list items introduced in #269

Sorry for this @irmerk @jeromesimeon but I think it would require a deeper dive into how the lists are being handled as other nodes are being lost as well while toggling the lists. Please see :

![Major-issue](https://user-images.githubusercontent.com/41413622/76422118-b6d24a80-63ca-11ea-8497-9e588040f2ff.gif)

**Comment by jeromesimeon** [comment]
@elit-altum I don't see any problem with this behaviour on the snapshot.

**Comment by elit-altum** [comment]
> 
> 
> @elit-altum I don't see any problem with this behaviour on the snapshot.

Is the ```---``` being lost on conversion of lists expected ?
