### ISSUE TITLE
Markdown Support: Adding Images

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#279]
**Is your feature request related to a problem? Please describe.**
The markdown editor should support rendering of images.

**Describe the solution you'd like**
1. A popup when the user clicks on the image button in the formatting toolbar (similar to what we have for links).
2. Rendering images directly when the user paste URL/drops image in the markdown.

**Additional context**
Slate supports both of these solutions but it is not functional yet.

**Comment by irmerk** [comment]
Reiterating what I mentioned in the other PR: Hold off on working on this - @dselman is migrating `markdown-editor` to the newest Slate (`v0.5x`), so once that is done we can resume work on this issue.

**Comment by dselman** [comment]
Work has started on this in the 0.50 branch.

**Comment by Michael-Grover** [comment]
Here is an icon for this feature

[image.svg.zip](https://github.com/accordproject/markdown-editor/files/4360189/image.svg.zip)
