### ISSUE TITLE
Block quotes crashes the markdown editor

### ISSUE THREAD

**Issue by 98lenvi** [accordproject/markdown-editor#282]
**Describe the bug**
Any method of creating blockquote crashes the entire editor

**To Reproduce**

Open [editor demo](https://accordproject-markdown-editor.netlify.com/), then

1. Place cursor Any text that is not a blockquote, for example 

> This is text. This is italic text. This is bold text. This is a link. This is inline code.

2. Click on blockquotes `"` via the toolbar or `CTRL` + `Q`
3. The editor crashes

Doesn't crash when placing the cursor on an existing blockquote, it converts the blockquote to a paragraph

**Expected behavior**
The above actions (1-3) shouldn't crash the editor

**What I think might be the cause**
A recent merged PR, this was not the behavior before.

**Comment by 98lenvi** [comment]
It crashes in [deploy preview for PR #277 ](https://deploy-preview-277--accordproject-markdown-editor.netlify.com/) but doesn't crash in [deploy preview for PR #275 ](https://deploy-preview-275--accordproject-markdown-editor.netlify.com/)

**Comment by irmerk** [comment]
Looking into this.

**Comment by irmerk** [comment]
Resolved with #283
