### ISSUE TITLE
Changing header text to bulleted list can sometimes break the editor

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/markdown-editor#286]
**To Reproduce**
1. Delete everything from the markdown editor
2. Create a line of text and make it a header 1, header 2, or header 3
3. Highlight the header text and change it to a bulleted list or numbered list
4. The text has now disappeared, and it is not possible to type any more text

https://www.loom.com/share/9ac04d7cd778464fb8047c91e7f3973d

**Comment by elit-altum** [comment]
@Michael-Grover This is due to the fact that the ```list_item``` only support ```paragraph``` as a child node.
Do we want to change it ?

**Comment by Michael-Grover** [comment]
I don't know, we may need input from @irmerk @DianaLease or @jeromesimeon

**Comment by irmerk** [comment]
@elit-altum I'm unsure about this. But if it involves the schema, I'm inclined to say we wait for the Slate `v0.5x` migration because I believe it does not use a schema anymore.

**Comment by irmerk** [comment]
Cannot reproduce.
