### ISSUE TITLE
in the first line of text, pressing backspace on an empty bulleted list should delete the bulleted list

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/markdown-editor#288]
When a user clicks backspace on an empty list element like this:

- 

The list element should disappear.

This is the case in the markdown editor for the most part, but not when the list element is the first line of text.

**Steps to reproduce**
1. Create a list element that's the first line of text in the editor
2. Click backspace until nothing is left in the list element
3. Now you can't delete the list element by pressing backspace

https://www.loom.com/share/cc5f0d39373f4ecb8950cf54a37082e1

**Comment by shakti97** [comment]
I would like to work on this issue

**Comment by Michael-Grover** [comment]
@shakti97 I've assigned you to the issue, thanks!

**Comment by shakti97** [comment]
Thanks, I started working on that,

**Comment by irmerk** [comment]
@shakti97 hold off on this until we finish the Slate migration, tracked [here](https://github.com/accordproject/markdown-editor/issues/297).

**Comment by nik72619c** [comment]
@shakti97 shall I take up this one if you are not working on it ?

**Comment by irmerk** [comment]
@nik72619c we are holding off for the Slate migration.

**Comment by irmerk** [comment]
@shakti97 @nik72619c:

#297 has been finished, so there is no longer a blocker on this issue. The migration _may_ have solved this issue, so look into that first.
