### ISSUE TITLE
Switch order of bulleted list and numbered list icons

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/markdown-editor#289]
Currently in the markdown editor toolbar, bulleted lists come before numbered lists, however the shortcuts we use for those formatting options imply that ordered lists come before bulleted lists.

Switch the order such that numbered lists are before bulleted lists so that the shortcuts make sense and so we match Google Docs, where we took the shortcuts from.

![image](https://user-images.githubusercontent.com/40569793/76562673-4126b700-647c-11ea-8c23-f9454b0fcab1.png)

![image](https://user-images.githubusercontent.com/40569793/76562693-4b48b580-647c-11ea-9ca8-38a3ab6d2204.png)

**Comment by jeromesimeon** [comment]
Just to clarify: the shortcuts are `⌘⇧7` for bulleted lists (which is nice since it's the same as `⌘*` so like the `*` in markdown) and `⌘⇧8`.

I like @Michael-Grover 's suggestion to keep the shortcuts but reverse the order of the buttons in the toolbar.

**Comment by jeromesimeon** [comment]
One more data point: the Slack markdown editor uses the same shortcuts as we do. It's probably a good idea to keep them.

<img width="137" alt="Screenshot 2020-03-12 at 4 24 50 PM" src="https://user-images.githubusercontent.com/670099/76563567-0faeeb00-647e-11ea-8417-bca93932848b.png">

**Comment by jeromesimeon** [comment]
Not sure whether this should be filed as a new issue, but a couple more comments. I personally like `⌘⇧8` rather than `⌘+⇧+8` in the shortcut hints.

**Comment by Michael-Grover** [comment]
I think we should use the word "shift" instead of the arrow pointing up. Personally I get confused when shortcuts use all of the icons because I don't have them memorized. My mac keyboard doesn't have an arrow pointing up on the shift key so I am not sure how someone would connect the arrow with "shift". The arrow also looks more like a house in my opinion. Looks like "home key"

**Comment by shrey-sachdeva2000** [comment]
Can I take this one?

**Comment by Michael-Grover** [comment]
Sorry @shrey-sachdeva2000 , a few minutes ago @elit-altum asked to take on this issue in the same PR as [this other issue](https://github.com/accordproject/markdown-editor/issues/290)

**Comment by Michael-Grover** [comment]
Thanks for offering! For some reason github won't let me assign @elit-altum to this issue to avoid confusion. @elit-altum can you assign yourself? Maybe you need to comment on the issue before I can assign you?

**Comment by elit-altum** [comment]
Sure @Michael-Grover 
I'd like to work on this!
