### ISSUE TITLE
Change code shortcut

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/markdown-editor#290]
The shortcut for making text look like code is currently cmd+alt+c and ctrl+alt+c opens the code inspector on Google Chrome (the most widely used browser). This is very disruptive and can be confusing to people who are not familiar with the browser code inspector. 

**Change the shortcut to ctrl(cmd)+shift+9 and place the code icon after the bulleted list and numbered list icons.**

According to this website, that shortcut doesn't conflict with any other software like Mac or Chrome
https://defkey.com/what-means/command-shift-9

![image](https://user-images.githubusercontent.com/40569793/76563185-49332680-647d-11ea-922b-ed22fc5ad548.png)

![image](https://user-images.githubusercontent.com/40569793/76563234-6831b880-647d-11ea-8de3-c6a25345e9f2.png)

**Comment by jeromesimeon** [comment]
I think I would avoid `Alt` altogether? This is the only shortcut using it, I believe?

For reference in Slack it's `⌘⇧c`
<img width="153" alt="Screenshot 2020-03-12 at 4 34 30 PM" src="https://user-images.githubusercontent.com/670099/76564653-64069a80-647f-11ea-9cfb-88dea899909c.png">

**Comment by Michael-Grover** [comment]
"cmd shift c" and "cmd alt c" open up the web inspector on my mac

**Comment by jeromesimeon** [comment]
I take it back `⌘⇧c` opens a kind of console on Safari too... so I like the `ctrl(cmd)+shift+9` idea. I would just make sure the number we pick corresponds to the order of the buttons (see https://github.com/accordproject/markdown-editor/issues/289)

**Comment by Michael-Grover** [comment]
we can't do ctrl(cmd)+shift+6 because that is the screenshot shortcut on mac, so to keep the button order consistent we should move the code icon to after the two list icons

**Comment by jeromesimeon** [comment]
Interesting: Slack in the browser (I'm using Safari) supports `⌘⇧c` and does not open the console. There must be a way to trap those calls...

<img width="1246" alt="Screenshot 2020-03-12 at 4 42 16 PM" src="https://user-images.githubusercontent.com/670099/76565266-94026d80-6480-11ea-853f-6a20372b2e01.png">

**Comment by elit-altum** [comment]
Can I work on this?

**Comment by Michael-Grover** [comment]
sure, thanks

**Comment by elit-altum** [comment]
> 
> 
> sure, thanks

Can I handle https://github.com/accordproject/markdown-editor/issues/289 in the same PR ?

**Comment by Michael-Grover** [comment]
Yeah I think that's a good idea

**Comment by Michael-Grover** [comment]
Since there are a lot of comments on this issue, I should clarify that I think we should do the following:

**Change the shortcut to ctrl(cmd)+shift+9 and place the code icon after the bulleted list and numbered list icons.**

**Comment by elit-altum** [comment]
In the tooptip should I use the word ```shift``` or the icon (⇧)?

**Comment by Michael-Grover** [comment]
What do the other tooltips currently use?

**Comment by elit-altum** [comment]
> 
> 
> What do the other tooltips currently use?

The icon only. But I wanted to know should we convert all to ```shift``` ? It's just a suggestion as some people might not be familiar with the icon.

**Comment by Michael-Grover** [comment]
Yeah there have been some discussions around this and I completely agree, can you change every use of the arrow icon to shift please?

**Comment by elit-altum** [comment]
Sure will do !

> 
> 
> Yeah there have been some discussions around this and I completely agree, can you change every use of the arrow icon to shift please?

Sure will do!

**Comment by Michael-Grover** [comment]
please mention in the PR the justification for changing the arrow icon to the word shift so that others viewing the PR understand why the change was made

**Comment by elit-altum** [comment]
@Michael-Grover Is this the required order ?
![image](https://user-images.githubusercontent.com/41413622/76633639-0c455d80-656b-11ea-9ffb-7c7cc63e7163.png)

**Comment by Michael-Grover** [comment]
yeah, so the shortcuts go ctrl+shift+7, ctrl+shift+7, ctrl+shift+9, right?

**Comment by elit-altum** [comment]
Yes they do! Will proceed to make a PR
