### ISSUE TITLE
Improved Hyperlink UI

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/markdown-editor#293]
I am working on an improved UI for hyperlinks using UIs from Google Docs, Jira, Medium, and others as inspiration. If you know of any good examples let me know.

I will update this issue when I'm done. Feel free to comment with examples of hyperlink UIs that you think work well.

Icon assets:
[hyperlink icons.zip](https://github.com/accordproject/markdown-editor/files/4339524/hyperlink.icons.zip)

This UI will appear when a user clicks on a hyperlink
https://projects.invisionapp.com/d/main#/console/16741009/409459591/preview
![image](https://user-images.githubusercontent.com/40569793/76785135-3ecda100-678b-11ea-8388-af3b63ae82af.png)

When a user hovers over one of the icons, there will be a hover effect like in the formatting toolbar, and a tooltip will appear stating what the button does.

- Copy link
- Delete link
- Open link in new tab

https://projects.invisionapp.com/d/main#/console/16741009/409459590/preview
![image](https://user-images.githubusercontent.com/40569793/76785160-4c832680-678b-11ea-996b-8a7d8f5d578f.png)

button styling:
https://projects.invisionapp.com/d/main#/console/16741009/409459590/preview
![image](https://user-images.githubusercontent.com/40569793/76785481-eb0f8780-678b-11ea-97aa-97b56ef39504.png)

You will need to request access on Invision to use the mockups. When you have access, click "inspect mode" on the bottom to see some of the design's css properties

![image](https://user-images.githubusercontent.com/40569793/76785551-08445600-678c-11ea-85ae-538e8aa297bc.png)

**Comment by Michael-Grover** [comment]
![image](https://user-images.githubusercontent.com/40569793/76662273-dfd21700-6553-11ea-9290-90aa8a2c23c2.png)

**Comment by Michael-Grover** [comment]
This is what I have so far. I like having one modal for everything instead of having a separate one for editing the link like Google and Jira do (see above for their UIs). feedback welcome. I will share final assets next week after getting some feedback.

![image](https://user-images.githubusercontent.com/40569793/76663563-c7fc9200-6557-11ea-980d-3d0adf7cc5a5.png)

**Comment by Michael-Grover** [comment]
![image](https://user-images.githubusercontent.com/40569793/76663683-1f026700-6558-11ea-86a6-d8a1357bb0fc.png)

**Comment by elit-altum** [comment]
Can I work on it along with https://github.com/accordproject/markdown-editor/pull/284?

**Comment by elit-altum** [comment]
Can I work on it along with https://github.com/accordproject/markdown-editor/pull/284?

**Comment by irmerk** [comment]
@elit-altum Yes that would work.

**Comment by Michael-Grover** [comment]
@elit-altum I have added more detail to the github issue, the design is ready to go. Let me know if you have any questions

**Comment by elit-altum** [comment]
Sure @Michael-Grover they look amazing!
I'd start working on it as soon as possible!

**Comment by elit-altum** [comment]
@Michael-Grover @irmerk currently I have created this much. Please review. Then I'll proceed to make the tooltips
![Implemented fix](https://user-images.githubusercontent.com/41413622/76839732-06e25e80-685c-11ea-90c6-7dacbf7052fd.png)

Some queries :
1. I have used ```flexbox``` for the layouts as they are only 1D layouts. Is that okay?
2. Currently I have used inline CSS styling for customising the ```Semantic-UI``` elements i.e used the ```style={{}}``` attribute. Should I switch to a customised ```styled.element``` instead, or is this approach fine?
Thank You!

**Comment by DianaLease** [comment]
> Some queries :
> 
> 1. I have used `flexbox` for the layouts as they are only 1D layouts. Is that okay?
> 2. Currently I have used inline CSS styling for customising the `Semantic-UI` elements i.e used the `style={{}}` attribute. Should I switch to a customised `styled.element` instead, or is this approach fine?
>    Thank You!

Hi @elit-altum !
1. Flexbox or css grid is fine for layouts!
2. I'd suggest avoiding inline styles and instead using `styled-components`. It's easier to read and re-use in the future if needed. If you are adding styles to a semantic-ui element, you'd use parentheses like [here]( https://github.com/accordproject/cicero-ui/blob/215cc84cfeecb2b6d5c0ee565b051e37a26ccf6b/src/ErrorLogger/styles.js#L47).

**Comment by Michael-Grover** [comment]
@elit-altum 

I just added you to the invision, sorry for the delay. Let me know if you still can't access the invision screens.

It looks great, thanks for providing screenshots. Here's my feedback:

The gray box should only appear on hover
![image](https://user-images.githubusercontent.com/40569793/76867644-341f1480-683c-11ea-989b-dfea7f1a97eb.png)

Use the button style from the invision (I understand you couldn't do that yet since I hadn't given you access to the invision)

"Link text" and "Link URL" appear to have inconsistent text styling in your screenshot
![image](https://user-images.githubusercontent.com/40569793/76868010-af80c600-683c-11ea-9c0a-56755ac1b76a.png)

**Comment by elit-altum** [comment]
@Michael-Grover on it!
