### ISSUE TITLE
Make "Insert a link" shortcut ⌘+K on mac and CTRL+K on Windows

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/markdown-editor#296]
Make "Insert a link" shortcut ⌘+K on mac and CTRL+K on Windows. Be sure to show the shortcut in the tooltip and use the correct one for each operating system. Make sure the tooltip is consistent with existing tooltips.

![image](https://user-images.githubusercontent.com/40569793/76767089-6f074680-676f-11ea-9935-d501d0cbc8ba.png)

**Comment by shrey-sachdeva2000** [comment]
Can I take this one? @Michael-Grover 
Although I'd like to point out that Ctrl+K shortcut directs me to the search box on Chrome.

**Comment by shrey-sachdeva2000** [comment]
Can I take this one? @Michael-Grover 
Although I'd like to point out that Ctrl+K shortcut directs me to the search box on Chrome. Should we go for Ctrl+Shift+K instead?

**Comment by Michael-Grover** [comment]
@shrey-sachdeva2000 is that on windows or Mac? I don't know about Windows but on Macs, cmd+K is the standard shortcut for creating a link. Even github on Mac uses cmd+k for creating a link. I am booting up my old windows desktop now to check what the standard shortcut on Windows is, however from what I can tell it is ctrl + k, consistent with Mac.

If Chrome uses this shortcut for something else, can we override it? How does this shortcut work in github, Google Docs, and others? Maybe they have a technique we can copy?

![image](https://user-images.githubusercontent.com/40569793/76866952-3c2a8480-683b-11ea-8fc5-0b308d2aec06.png)

**Comment by algomaster99** [comment]
@Michael-Grover @DianaLease @irmerk 
I was working on this issue and I needed some help.
1. `case isHotKey('mod+shift+k', event) && isEditable(editor, CONST.HYPERLINK):`
I  have added this line in `SlateAsInputEditor/index.js`
2. This case will invoke a function which shall change the state of the 'SetLinkForm'.
3. In the same file, I added these two lines as well:
```
  const [openSetLink, setLinkFormVisibility] = useState(false);
  const toggleLinkFormVisibility = () => setLinkFormVisibility(prevState => {
    return {...prevState, openSetLink: true};
  }); 
```
And then I passed this openSetLink state to `FormattingToolbar/index.js`. But somehow `toggleLinkFormVisibility` function is not working for me. It is not toggling the visibility of the form.

**Comment by irmerk** [comment]
It looks like @shrey-sachdeva2000 is working on this one.

Still, @algomaster99, I'm not sure I follow the logic for `toggleLinkFormVisibility`. Could you show more of the code you have so it may be a bit more clear?

**Comment by algomaster99** [comment]
@irmerk Shall I make a draft PR for this one?

**Comment by irmerk** [comment]
This is getting a bit too involved prior to [migration to slate `v0.5x`](https://github.com/accordproject/markdown-editor/issues/297). I'm working on that this week, so we can revisit this issue after.

**Comment by shrey-sachdeva2000** [comment]
[acsc](url)

> @shrey-sachdeva2000 is that on windows or Mac? I don't know about Windows but on Macs, cmd+K is the standard shortcut for creating a link. Even github on Mac uses cmd+k for creating a link. I am booting up my old windows desktop now to check what the standard shortcut on Windows is, however from what I can tell it is ctrl + k, consistent with Mac.
> 
> If Chrome uses this shortcut for something else, can we override it? How does this shortcut work in github, Google Docs, and others? Maybe they have a technique we can copy?
> 
> ![image](https://user-images.githubusercontent.com/40569793/76866952-3c2a8480-683b-11ea-8fc5-0b308d2aec06.png)

This behaviour is on Windows. And yes, we can override this. Actually, the only time Ctrl+K would open a query search is when the focus of the cursor is not inside the editor. The same thing happens with GitHub, Ctrl+K for links only works when the focus is inside the textarea and some text is selected.

**Comment by Moizsohail** [comment]
I would like to work on this feature request

**Comment by Michael-Grover** [comment]
@Moizsohail this issue is on hold as per @irmerk's comment earlier

> This is getting a bit too involved prior to [migration to slate `v0.5x`](https://github.com/accordproject/markdown-editor/issues/297). I'm working on that this week, so we can revisit this issue after.

And it looks like @shrey-sachdeva2000 is already working on this. I just assigned the issue to him now to avoid any confusion

**Comment by irmerk** [comment]
@algomaster99 @shrey-sachdeva2000 @Moizsohail:

#297 has been finished, so there is no longer a blocker on this issue. Confer with @DianaLease who is working on getting the hyperlink modal support again. #302 is tracking this.
