### ISSUE TITLE
Migrate to Slate 0.50.x

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#297]
The editor needs to be updated to use Slate 0.50.x. This is a major release of Slate with many breaking changes.

This work is underway in the `slate-0.50.x-hack` branch. Note that you also need to `npm link` to the `accordproject/markdown-slate` on the `slate-0.50.x` branch.

If you want to paste HTML `img` tags you will also need to `npm link` to `@accordproject/markdown-html` on the `slate-0.50.x` branch.

## DOM
- [x] Paragraph
- [x] Bold
- [x] Italic
- [x] Code
- [x] Code Block
- [x] HTML Block
- [x] HTML Inline
- [x] Headings
- [x] Image
- [x] Link
- [x] HR
- [x] Linebreak
- [x] Softbreak
- [x] OL
- [x] UL

## Misc
- [x] Markdown load/save
- [x] Read-only
- [x] Schema
- [x] Copy & Paste HTML
- [x] use styled components 
- [ ] update css
- [ ] styling props
- [x] Hot keys
- [ ] check dependencies and production build

## Toolbar
- [x] Toolbar
- [x] Insert Image
- [ ] Insert/Edit Link

**Comment by irmerk** [comment]
Closing, still working on hyperlink support, but now everyone can start work off `master` again.
