### ISSUE TITLE
Make "Insert Image" Shortcut ⌘+Shift+G on Mac and Ctrl+Shift+G on Windows

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#313]
Make a "Insert Image" shortcut `Ctrl+Shift+G` on Windows and `⌘+Shift+G` on Mac. Also change the tooltip of the "Insert Image" button to show the shortcut.

**Comment by irmerk** [comment]
I think this is being tracked in #296

**Comment by shrey-sachdeva2000** [comment]
> I think this is being tracked in #296

Isn't #296 to add shortcut support for hyperlinks only?

**Comment by irmerk** [comment]
Oof, yes, I'm on a roll today of not being able to read correctly.

**Comment by shrey-sachdeva2000** [comment]
Thanks! Please assign this to me. Also, does `mod+shift+G` hotkey for inserting images sound good?

**Comment by irmerk** [comment]
@Michael-Grover thoughts?

**Comment by Michael-Grover** [comment]
Google Docs, Microsoft Word, and github don't use shortcuts for inserting images, so it appears that it's not common to use a shortcut for this, but I guess it wouldn't hurt. Is there any precedent for mod+shift+G being the shortcut for adding images? Is the shortcut used for anything else by Windows, Mac, Chrome, Firefox, etc. that might cause issues?

**Comment by shrey-sachdeva2000** [comment]
> Google Docs, Microsoft Word, and github don't use shortcuts for inserting images, so it appears that it's not common to use a shortcut for this, but I guess it wouldn't hurt. Is there any precedent for mod+shift+G being the shortcut for adding images? Is the shortcut used for anything else by Windows, Mac, Chrome, Firefox, etc. that might cause issues?

MS Word uses `Alt+N+P` for inserting images but [Stackedit](https://stackedit.io/app#) is a popular online markdown editor that uses `Ctrl+Shift+G`, it also aligns well with the pattern of shortcuts we currently have. It doesn't look like this shortcut is being used by anything else, I tried it on Chrome and Firefox. Will send in a PR for this shortly.
