### ISSUE TITLE
Make ToolbarMenu Sticky

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#314]
**Is your feature request related to a problem? Please describe.**
The `ToolbarMenu` is not sticky so formatting might be an issue when the contract becomes long as the toolbar won't be visible.

**Describe the solution you'd like**
The `ToolbarMenu` should be sticky and attach to the top of the editor when the user scrolls so it is in view when scrolling through long contracts.

**Additional context**
I'd like to work on this.

**Comment by irmerk** [comment]
@Michael-Grover @DianaLease thoughts?

I'd like to see how this looks when used in the `ContractEditor` in `cicero-ui`

**Comment by DianaLease** [comment]
Yes, I believe this should be sticky. It used to be sticky prior to the slate migration.
