### ISSUE TITLE
Heading One not preserved on Paste

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#319]
**Describe the bug**
Copy/paste within the editor doesn't preserve H1.

**To Reproduce**
1. Go to https://cicero-ui.netlify.com
2. Select "Heading One" as well as the first paragraph.
3. Press CTRL-C to copy
4. Place cursor after "this is inline code" on a newline
6. Press CTRL-V to paste
7. Note that "Heading One" is inserted as normal text. The rest of the formatting is preserved.

**Expected behavior**
Headings should retain formatting on paste.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari
 - Version 13.1

**Comment by irmerk** [comment]
This is only happening when the header is the beginning of the fragment copied.

**Comment by irmerk** [comment]
This issue actually exists in the [Slate rich text example](https://www.slatejs.org/examples/richtext). Filing an issue in Slate.

**Comment by irmerk** [comment]
Issue is being tracked already https://github.com/ianstormtaylor/slate/issues/3320
