### ISSUE TITLE
Copy Paste Hyperlink Issue

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#324]
**Describe the bug**
A user experiences incorrect results pasting in links.

**To Reproduce**
1. Go to the [live demo](https://accordproject-markdown-editor.netlify.com/)
2. Create a new paragraph
3. Paste in `https://github.com/accordproject`
4. Press `Enter`
5. See markdown on the left incorrect (first screenshot)
6. Paste and press `Enter` as many times as you wish
7. See compounding issue (second screenshot)

**Expected behavior**
Pasting links should behave as expected.

**Screenshots**
<img width="1516" alt="Screen Shot 2020-04-13 at 10 14 33 AM" src="https://user-images.githubusercontent.com/36460856/79127321-b2090980-7d6f-11ea-8291-76fd56a79059.png">
---
<img width="1484" alt="Screen Shot 2020-04-13 at 10 16 53 AM" src="https://user-images.githubusercontent.com/36460856/79127469-f5fc0e80-7d6f-11ea-8f65-6287b2fc3bba.png">

**Comment by dselman** [comment]
How did you paste the link? When I do it (Safari) it just inserts the text of the link.

**Comment by irmerk** [comment]
Copy the URL, `MOD + V` in the editor.

**Comment by irmerk** [comment]
This was fixed in #340
