### ISSUE TITLE
Hyperlink Button crashes Editor after Applying Link

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#328]
**Describe the bug**
Selecting the Hyperlink button from the `ToolbarMenu` on selecting an existing link crashes the demo.

**To Reproduce**
1. Go to the [demo](https://accordproject-markdown-editor.netlify.com/)
2. Create a Hyperlink
3. Click on Apply
4. Click on Hyperlink button in `ToolbarMenu`
5. Demo crashes

**Expected behavior**
The Hyperlink modal should open again.

**Screenshots**
![Markdown Editor (2)](https://user-images.githubusercontent.com/47667325/79128862-d2fa4a80-7dc1-11ea-9713-45d99d823a24.gif)

**Comment by irmerk** [comment]
Oof that's a good one.
