### ISSUE TITLE
Rich Text Editor Overlaps Markdown Text Editor

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#334]
**Describe the bug**
When the `TextArea` of `MarkdownTextEditor` is resized to increase its width, the `RichTextEditor` overlaps the `TextArea` resize button and the `MarkdownTextEditor`  can't be resized again.

**To Reproduce**
1. Go to the [demo](https://accordproject-markdown-editor.netlify.com/)
2. Click on the `Markdown Text Editor` resize button
3. Increase its width
4. The `Markdown Text Editor` can't be resized again

**Expected behavior**
Either the `MarkdownTextEditor` should have a fixed width so the contents of both the Editors
don't overlap _or_ the `MarkdownTextEditor` should still be resizable.

**Screenshots**
![Markdown Editor (4)](https://user-images.githubusercontent.com/47667325/79148800-bff87200-7de3-11ea-94d1-5f3f09b90e49.gif)

**Additional Context**
I'd like to work on this!

**Comment by Michael-Grover** [comment]
Would it be difficult to make the border between the two editors movable, instead of dragging on the edge of one editor just changing the size of one editor but not the other? For example if I move the border right to expand the editor on the left, the editor on the right will automatically become smaller to accommodate. Like how you can move the borders between editors in codepen

https://codepen.io/msdr/pen/LYYPqpa

**Comment by shrey-sachdeva2000** [comment]
Thats sounds great! I created a prototype using [React Resizable](https://www.npmjs.com/package/react-resizable). It looks like this:

![Markdown Editor (8)](https://user-images.githubusercontent.com/47667325/79218434-08f50880-7e6e-11ea-81f0-cf9ed408f53a.gif)

Although, I think its better to not keep the `RichTextEditor` resizable because our `ToolbarMenu` would go out of proportion and snap. Something like this: 

![Markdown Editor (6)](https://user-images.githubusercontent.com/47667325/79217302-422c7900-7e6c-11ea-9f67-45a0a507c752.gif)

So, only the `MarkdownEditor` would be resizable and its max-width would be set to its original width so it doesn't collapse the `RichTextEditor`. 

![Markdown Editor (7)](https://user-images.githubusercontent.com/47667325/79217202-114c4400-7e6c-11ea-9566-9bf34a067bee.gif)


Please let me know your thoughts on this! @Michael-Grover @DianaLease @irmerk

**Comment by Michael-Grover** [comment]
the third option looks good. Can we use this cursor instead of the diagonal one when resizing the box?
![image](https://user-images.githubusercontent.com/40569793/79237527-40e35800-7e3c-11ea-81a5-7f7f0831f5bd.png)

**Comment by irmerk** [comment]
Still reading this and the PR you have, but I don't think this should even be scrollable. This is a demo so it should just be the markdown on the left and the rich text on the right. We should be able to avoid all this by just making them static.
