### ISSUE TITLE
Lists Break on Enter

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#335]
**Describe the bug**
Pressing <kbd>Enter</kbd> on an item in the List doesn't create a new item in the List.

**To Reproduce**
1. Go to the [demo](https://accordproject-markdown-editor.netlify.com/)
2. Click on a List item
3. Press <kbd>Enter</kbd>
4. A new line is created instead of List item

**Expected behavior**
On pressing <kbd>Enter</kbd>, a new list item should be created. While, on pressing <kbd>Shift+Enter</kbd> a new line within the same item should be created.

**Screenshots**
![lists](https://user-images.githubusercontent.com/47667325/79151713-8d04ad00-7de8-11ea-9c80-9b94008ef464.PNG)

**Comment by Michael-Grover** [comment]
I want to add to this that pressing enter once should create a new list item, but pressing enter twice (or once on the new empty list item) should remove the list item and exit the list. See how Google Docs works

**Comment by irmerk** [comment]
Opened an issue within Slate tracking this [here](https://github.com/ianstormtaylor/slate/issues/3624).
