### ISSUE TITLE
Preview Text Covers Entire Height

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#339]
**Describe the bug**
The vertical divider text "Preview" covers entire height of the editor so the text overlapping it is not selectable.

**To Reproduce**
1. Go to the [demo](https://accordproject-markdown-editor.netlify.com/)
2. Try to click on any text after the vertical divider text "Preview" from the initial initial text position.

**Expected behavior**
The text should be selectable.

**Screenshots**
![preview](https://user-images.githubusercontent.com/47667325/79156355-5d59a300-7df0-11ea-9f0f-026225363bdd.PNG)

**Comment by irmerk** [comment]
Combining with #337
