### ISSUE TITLE
Incorrect Cursor Position on Enter

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [accordproject/markdown-editor#341]
**Describe the bug**
Pressing <kbd>Enter</kbd> before/after a formatted text changes line but not the cursor position. 

**To Reproduce**
1. Go to the [demo](https://accordproject-markdown-editor.netlify.com/)
2. Click before/after formatted text (codeblocks, blockquotes, italics, bold)
3. Press <kbd>Enter</kbd>
4. The text enters a new line but the cursor position remains the same

**Expected behavior**
The cursor position should be at the starting of the new line.

**Screenshots**
![cursor_position](https://user-images.githubusercontent.com/47667325/79159439-b11abb00-7df5-11ea-9a40-3a334368ddf5.PNG)

**Comment by elit-altum** [comment]
@shrey-sachdeva2000 @irmerk Can I take a look at this?

**Comment by elit-altum** [comment]
@dselman @irmerk Could you please guide me where this might be coming from?
I noticed something, that hitting enter in the formatted text works correctly. The cursor position only misbehaves if we press enter **after** the formatted text.

**Comment by dselman** [comment]
Can you reproduce this with any of the Slate demos?

**Comment by irmerk** [comment]
Yes in [this demo](https://www.slatejs.org/examples/richtext) click at the end of "**rich**" and press enter.

**Comment by dselman** [comment]
Can you create an issue on the Slate repo please? Someone in the Slate community may have a fix or workaround.

**Comment by elit-altum** [comment]
Yes 

> 
> 
> Yes in [this demo](https://www.slatejs.org/examples/richtext) click at the end of "**rich**" and press enter.

Yup it seems to be an issue with Slate only. Should I open an issue there @irmerk ?

**Comment by irmerk** [comment]
Yes feel free @elit-altum, you can see some issue's I've opened there for format reference.

**Comment by irmerk** [comment]
I made an issue (https://github.com/ianstormtaylor/slate/issues/3642)

**Comment by elit-altum** [comment]
@irmerk Should we close this now ?
