### ISSUE TITLE
Reimplement formatting toolbar

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#35]
The existing floating toolbar has been disabled during the port to the latest version of React. We should implement a static formatting toolbar that can be attached to the top of the editor.

**Comment by Michael-Grover** [comment]
https://projects.invisionapp.com/d/main#/console/16741009/364322244/preview
![image](https://user-images.githubusercontent.com/40569793/58038130-16d6c800-7afd-11e9-92fd-5b09e5828694.png)

assets:
[icons.zip](https://github.com/accordproject/markdown-editor/files/3198906/icons.zip)

**Comment by Michael-Grover** [comment]
Updated:

https://projects.invisionapp.com/d/main#/console/16741009/364322244/preview
![image](https://user-images.githubusercontent.com/40569793/58048049-be60f400-7b17-11e9-8552-f68978b3bcc5.png)

Assets:
[icons.zip](https://github.com/accordproject/markdown-editor/files/3199618/icons.zip)

**Comment by irmerk** [comment]
Next step: #20

**Comment by dselman** [comment]
The vast majority of this has been completed. I'm going to close this and we will treat any remaining work as additional standalone enhancements.
