### ISSUE TITLE
Ctrl/Cmd+ Z doesn't undo link removal

### ISSUE THREAD

**Issue by elit-altum** [accordproject/markdown-editor#352]
**Describe the bug**
- Using ```ctrl/cmd + z``` doesn't restore the link after removing it

**To Reproduce**
1. Go to https://accordproject-markdown-editor.netlify.com/
2. Click on 'link'
3. Remove the link using the link modal
4. Use the shortcut to undo the changes
5. The link remains as is

**Expected behavior**
The original link should be restored

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome 
 - Version: 80.0

**Additional context**
- Using the 'undo' button from the toolbar does restore the link

**Comment by elit-altum** [comment]
@irmerk Can I take a look at this ?

**Comment by nik72619c** [comment]
@elit-altum are you still working on this?

**Comment by elit-altum** [comment]
> @elit-altum are you still working on this?

Yup @nik72619c

**Comment by elit-altum** [comment]
@irmerk I can't pinpoint where this might be coming from, can you please guide me a bit please ?
Thank You!

**Comment by dselman** [comment]
Interesting that the undo button works, which indicates that it is not a Slate issue (at least not an issue with the undo buffer). I would look at how the keypress is being handled. Perhaps it is a focus issue with the modal stealing focus from the editor?

**Comment by elit-altum** [comment]
Thank you for this @dselman !
I will take a look into this
