### ISSUE TITLE
Delete Image Functionality missing while selecting it

### ISSUE THREAD

**Issue by kanav-raina** [accordproject/markdown-editor#356]
**Is your feature request related to a problem? Please describe.**
    The markdown editor should support deletion of inserted images. After clicking on the inserted images you are not able to delete it.

**Describe the solution you'd like**
   Image should be deleted by pressing backspace or delete key.

**Comment by irmerk** [comment]
Yeah interesting. If you are in front of the image you can backspace, but not while selecting it.

**Comment by arteevraina** [comment]
hello @kanav-raina ! Are you still able to reproduce this issue?

**Comment by irmerk** [comment]
I just did, this issue still exists.

**Comment by kanav-raina** [comment]
hello @arteevraina , yes I am able to reproduce it.
you can backspace the image but when you click on the image and then press delete or backspace, it's not getting deleted.
