### ISSUE TITLE
Blockquotes not preserving Headings

### ISSUE THREAD

**Issue by arteevraina** [accordproject/markdown-editor#362]
**Describe the bug**
When `Blockquotes` are applied on `Headings` they become `Normal`

**To Reproduce**
1. Go to [demo](https://accordproject-markdown-editor.netlify.app/)
2. Select any heading.
3. Select `Blockquote`.

**Expected behavior**
Headings should be preserved on using `Blockquotes`.

**Comment by arteevraina** [comment]
Hi @irmerk ! I am not able to reproduce this issue anymore now.

**Comment by jeromesimeon** [comment]
> Hi @irmerk ! I am not able to reproduce this issue anymore now.

Might have been fixed in the migration to Slate57 ?
