### ISSUE TITLE
Hyperlink Modal accepts invalid link values

### ISSUE THREAD

**Issue by nik72619c** [accordproject/markdown-editor#365]
**Describe the bug**
The hyperlink modal accepts invalid link URLs. For eg:- a space, normal strings, etc.

**To Reproduce**
1. select a text
2. Click on the `Link` button on the top to convert the text to a link
3. enter an invalid link
4. The text converts to a link which points to the invalid link URL

**Expected behavior**
An error or at least a warning message should be displayed, to alert the user that the link mentioned is invalid

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by nik72619c** [comment]
@DianaLease @dselman I feel we can integrate `react-form` into this to apply validations. Would love to hear your thoughts on this :)

**Comment by irmerk** [comment]
I think Google Docs allows this. @Michael-Grover?

**Comment by DianaLease** [comment]
> @DianaLease @dselman I feel we can integrate `react-form` into this to apply validations. Would love to hear your thoughts on this :)

If we add a library, I'm a fan of using https://github.com/final-form/react-final-form as it is well-maintained and lightweight while still offering a lot!

**Comment by Michael-Grover** [comment]
I believe in another issue there was a decision that this error validation isn't necessary but I can't find it

**Comment by nik72619c** [comment]
I am getting this error, after installing `react-final-form`, can someone help?

<img width="935" alt="Screenshot 2020-04-21 at 9 02 44 PM" src="https://user-images.githubusercontent.com/30630904/79885107-df128780-8413-11ea-969a-e51057dfd41d.png">

**Comment by nik72619c** [comment]
Fixed.
Also, I wanted to ask if we would require a validation library such as `react-final-form` in this case?
There are not many validations required since the repo is not using forms extensively?

**Comment by Michael-Grover** [comment]
I don't think this is necessary. Google Docs doesn't do this kind of validation. Are there examples of this kind of hyperlink validation in any prominent apps?

**Comment by irmerk** [comment]
Yeah I don't think this needs to be that thorough. If the URL does not begin with `http://` or `https://`, add it. That should probably be the extent we do at this point.

**Comment by nik72619c** [comment]
> Yeah I don't think this needs to be that thorough. If the URL does not begin with `http://` or `https://`, add it. That should probably be the extent we do at this point.

@irmerk shouldn't the logic be that if the URL begins with `http://` or `https://`, add it ?

**Comment by irmerk** [comment]
I don't think we want to be that prescriptive of what a user enters as a URL

**Comment by nik72619c** [comment]
oh okay, can we close this up then? @irmerk

**Comment by irmerk** [comment]
> Yeah I don't think this needs to be that thorough. If the URL does not begin with `http://` or `https://`, add it. That should probably be the extent we do at this point.

We can implement this change.

**Comment by nik72619c** [comment]
got it, thanks :)
Sending a PR shortly
