### ISSUE TITLE
Block quotes can't be escaped

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/markdown-editor#372]
To reproduce bug:
1. Create a block quote
2. type something in it.
3. Press enter to create another block quote
4. Press enter again in the new empty block quote, deleting the new block quote and moving the cursor back to the previous block quote
5. Repeat steps 3 and 4 to infinity

Solution:
Pressing enter in a block quote escapes the block quote. Pressing shift+enter creates a new line within the block quote.

See video
https://www.loom.com/share/fed85a7d07e441db8a8e7ef145f20cc9?source_email=loom-video-first-view-updated

**Comment by irmerk** [comment]
This may be fixed with #371
