### ISSUE TITLE
Convert multiple items to list doesn't display list separator

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#392]
Select multiple lines of normal text and convert to a list. The list item separators (numbers or bullets do not show up).

**To Reproduce**
1. Enter multiple lines of text
2. Select the lines
3. Press the ol or ul list buttons
4. Note that the text is indented but it doesn't get the bullet or number. Pressing the button twice will insert the bullet or number.

**Expected behavior**
List items should use a separator

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari
 - Version 13.1

**Comment by irmerk** [comment]
I can't replicate this in the [demo](https://accordproject-markdown-editor.netlify.app/)
