### ISSUE TITLE
Toolbar has rendering and functional issues on Safari

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#62]
**Describe the bug**
The toolbar icons seem to be a little mis-aligned on Safari
Some of the toolbar buttons don't seem to always work on Safari, depending on the selection in the document.

**To Reproduce**
1. Run using the latest Safari on Mac OS X

**Expected behavior**
Toolbar should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari
 - Version Latest

**Comment by dselman** [comment]
<img width="553" alt="Screenshot 2019-06-24 at 22 11 40" src="https://user-images.githubusercontent.com/623108/60052413-14075e00-96cd-11e9-9397-75f30eab7ac1.png">

Icons appear clipped at base.

**Comment by irmerk** [comment]
Notes on a rendering error while inspecting the functionality issue:

I ran into an issue with `npm link`. Essentially, while no errors were presented in the console, a React component in a folder was just not being executed/rendered. This was replicated by @DianaLease 

Steps to reproduce:
1. Download `@accordproject/markdown-editor` and `@accordproject/cicero-ui` and run `npm install` in both
2. Run `npm link` in `markdown-editor` 
3. Remove `@accordproject/markdown-editor` from `cicero-ui`'s `node_modules` folder
4. Run `npm link @accordproject/markdown-editor` in `cicero-ui`
5. Run `npm run start`, ensure running `npm run transpile` in `markdown-editor` triggers a recompile in `cicero-ui`
6. Note that the `FormatToolbar` is not rendering (when the containing folder is `FormatToolbar`, not `FormattingToolbar`) - in `src/SlateAsInputEditor/index.js` give `ToolbarWrapper` a border, add something custom (console logs) to the return of `FormatToolbar` from `src/FormatToolbar/index.js`
7. Note that nothing in the `FormatToolbar` is being executed - no console logs
8. Create a new folder (`src/NewFolder`) and move all `src/FormatToolbar` files into it - adapt the imports
9. Note that the `FormatToolbar` is now rendering

Unsure what the cause of this would be. Thoughts are `webpack`, `babel`, or `npm link`. Was hoping to raise an issue in the respective codebase, but that may not be likely.

**Comment by irmerk** [comment]
#72 will correct the functionality - Safari does not support `onPointerDown`.

The issue with icon clipping may be because I very specifically set the size, margin, padding, etc. for each icon to make it fit. One of those must be slightly off from Chrome -> Safari. Will be looking into this.

**Comment by irmerk** [comment]
Finished with #72 and #73
