### ISSUE TITLE
Support readOnly prop Dictating Toolbar Rendering

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#79]
**Is your feature request related to a problem? Please describe.**
This component should accept an optional prop `readOnly` which toggles the toolbar rendering or not

**Describe the solution you'd like**
Conditionally render the toolbar based on the `readOnly` prop

**Describe alternatives you've considered**
N/A

**Additional context**
This relates to:
- Issue #35
- Issue #78

**Comment by codingdefined** [comment]
I would like to work on it. In the current state, SlateAsInputEditor takes readOnly props but that is for Editor, should we combine it or create additional props say readOnlyToolbar to render Toolbar based on it's value?

**Comment by irmerk** [comment]
Great @codingdefined! I think we should be creating an additional prop (`readOnlyToolbar`) as you said. `readOnly` will be for whether or not you can type in the editor, so it will be different.

**Comment by irmerk** [comment]
Start at the work done in #112
