### ISSUE TITLE
List Blocks Register as Hyperlink

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#84]
**Describe the bug**
Creating a bulleted list marks a block as a hyperlink

**To Reproduce**
1. Go to [TSv2](https://accordproject-studio.netlify.com/)
2. Note that the hyperlink and list toolbar icons are not highlighted
3. Select text, click on bulleted list
4. Note the bulleted list **and** hyperlink icons are highlighted now

**Expected behavior**
Hyperlink should be separate from list nodes

**Screenshots**
Before:
<img width="1680" alt="Screen Shot 2019-08-28 at 10 17 47 AM" src="https://user-images.githubusercontent.com/36460856/63864319-a05c2880-c97d-11e9-862c-4ae63f342cd2.png">
After:
<img width="1680" alt="Screen Shot 2019-08-28 at 10 18 58 AM" src="https://user-images.githubusercontent.com/36460856/63864335-a7833680-c97d-11e9-932f-13da2d45642e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrome and Safari

**Additional context**
N/A

**Comment by irmerk** [comment]
@sgbj

**Comment by sgbj** [comment]
I'm here. 👋
